-- seed.sql: destinations then tours (matches actual production schema)
-- Run against your D1 database:
--   npx wrangler d1 execute travelbyfz_db --local --file=..\..\packages\db\src\seed.sql
--   (add --remote once you're ready to seed the production database)
--
-- Safe to re-run: uses WHERE NOT EXISTS guards keyed on unique `slug` columns
-- since D1/SQLite's ON CONFLICT needs a matching unique index target, and this
-- pattern avoids relying on that if your migration hasn't created it yet.

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Alleppey', 'alleppey', 'Kerala', 'South India', 'Known as the Venice of the East, famous for tranquil backwater cruises on traditional houseboats.', 'Known as the Venice of the East, famous for tranquil backwater cruises on traditional houseboats.', 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'alleppey');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Jaipur → Jodhpur → Udaipur', 'jaipur-jodhpur-udaipur', 'Rajasthan', 'North India', 'Rajasthan''s royal circuit of forts, palaces, and desert cities.', 'Rajasthan''s royal circuit of forts, palaces, and desert cities.', 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'jaipur-jodhpur-udaipur');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Kaza', 'kaza', 'Himachal Pradesh', 'North India', 'A remote high-altitude cold desert valley in the Trans-Himalayas.', 'A remote high-altitude cold desert valley in the Trans-Himalayas.', 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'kaza');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Badrinath · Kedarnath · Gangotri · Yamunotri', 'badrinath-kedarnath-gangotri-yamunotri', 'Uttarakhand', 'North India', 'The four sacred Himalayan shrines forming India''s most revered pilgrimage circuit.', 'The four sacred Himalayan shrines forming India''s most revered pilgrimage circuit.', 'https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'badrinath-kedarnath-gangotri-yamunotri');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Madikeri', 'madikeri', 'Karnataka', 'South India', 'A misty hill town in Karnataka famed for coffee plantations and waterfalls.', 'A misty hill town in Karnataka famed for coffee plantations and waterfalls.', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'madikeri');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Port Blair · Havelock', 'port-blair-havelock', 'Andaman & Nicobar', 'Islands', 'A tropical archipelago known for coral reefs, scuba diving, and colonial history.', 'A tropical archipelago known for coral reefs, scuba diving, and colonial history.', 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'port-blair-havelock');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Varanasi', 'varanasi', 'Uttar Pradesh', 'North India', 'One of the world''s oldest living cities, sacred to Hindus along the Ganges.', 'One of the world''s oldest living cities, sacred to Hindus along the Ganges.', 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'varanasi');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Manali', 'manali', 'Himachal Pradesh', 'North India', 'A Himalayan resort town popular for snow adventure and mountain passes.', 'A Himalayan resort town popular for snow adventure and mountain passes.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'manali');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'North & South Goa', 'north-south-goa', 'Goa', 'West India', 'India''s coastal getaway known for beaches, nightlife, and Portuguese heritage.', 'India''s coastal getaway known for beaches, nightlife, and Portuguese heritage.', 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'north-south-goa');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Ooty', 'ooty', 'Tamil Nadu', 'South India', 'A colonial-era hill station in the Nilgiris known for tea estates and cool climate.', 'A colonial-era hill station in the Nilgiris known for tea estates and cool climate.', 'https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'ooty');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Delhi · Agra · Jaipur', 'delhi-agra-jaipur', 'Multi-State', 'North India', 'India''s classic tourist circuit spanning the capital, the Taj Mahal, and the Pink City.', 'India''s classic tourist circuit spanning the capital, the Taj Mahal, and the Pink City.', 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'delhi-agra-jaipur');

INSERT INTO destinations (id, name, slug, state, region, short_description, description, cover_image, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'Leh · Nubra · Pangong', 'leh-nubra-pangong', 'Ladakh', 'North India', 'A high-altitude Himalayan region famed for dramatic landscapes and mountain passes.', 'A high-altitude Himalayan region famed for dramatic landscapes and mountain passes.', 'https://images.unsplash.com/photo-1597040663342-45b6af3d91a5?w=600&q=80', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM destinations WHERE slug = 'leh-nubra-pangong');


INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Kerala Backwaters & Spice Trail', 'kerala-backwaters', 'TBF-KERALA-BAC-101', 'Beach', 'group', 'Kerala Backwaters & Spice Trail covering Alleppey in Kerala — a 5 day 4 night beach experience.', 'Kerala Backwaters & Spice Trail covering Alleppey in Kerala — a 5 day 4 night beach experience.', 5, 4, 'Kochi', 'Alleppey', 18500, 'INR', 12, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Houseboat stay", "Spice plantation", "Kathakali show"]', 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80', 4.9, 312, 0, 1, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'alleppey'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'kerala-backwaters');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Royal Rajasthan Heritage Tour', 'rajasthan-royals', 'TBF-RAJASTHAN-102', 'Cultural', 'group', 'Royal Rajasthan Heritage Tour covering Jaipur → Jodhpur → Udaipur in Rajasthan — a 7 day 6 night cultural experience.', 'Royal Rajasthan Heritage Tour covering Jaipur → Jodhpur → Udaipur in Rajasthan — a 7 day 6 night cultural experience.', 7, 6, 'Jaipur', 'Udaipur', 24999, 'INR', 10, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Amber Fort", "Desert safari", "Lake Pichola cruise"]', 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80', 4.8, 198, 0, 1, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'jaipur-jodhpur-udaipur'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'rajasthan-royals');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Spiti Valley Expedition', 'spiti-valley', 'TBF-SPITI-VALL-103', 'Adventure', 'group', 'Spiti Valley Expedition covering Kaza in Himachal Pradesh — a 8 day 7 night adventure experience.', 'Spiti Valley Expedition covering Kaza in Himachal Pradesh — a 8 day 7 night adventure experience.', 8, 7, 'Shimla', 'Kaza', 32000, 'INR', 8, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Key Monastery", "Chandratal Lake", "4WD off-roading"]', 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80', 4.7, 145, 0, 1, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'kaza'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'spiti-valley');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Char Dham Yatra', 'char-dham', 'TBF-CHAR-DHAM-104', 'Religious', 'group', 'Char Dham Yatra covering Badrinath · Kedarnath · Gangotri · Yamunotri in Uttarakhand — a 12 day 11 night religious experience.', 'Char Dham Yatra covering Badrinath · Kedarnath · Gangotri · Yamunotri in Uttarakhand — a 12 day 11 night religious experience.', 12, 11, 'Haridwar', 'Badrinath', 42000, 'INR', 15, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["4 sacred shrines", "Helicopter option", "Vedic rituals"]', 'https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=600&q=80', 4.9, 421, 0, 1, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'badrinath-kedarnath-gangotri-yamunotri'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'char-dham');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Coorg Coffee & Nature Retreat', 'coorg-retreat', 'TBF-COORG-RETR-105', 'Hill Station', 'group', 'Coorg Coffee & Nature Retreat covering Madikeri in Karnataka — a 4 day 3 night hill station experience.', 'Coorg Coffee & Nature Retreat covering Madikeri in Karnataka — a 4 day 3 night hill station experience.', 4, 3, 'Bengaluru', 'Madikeri', 14500, 'INR', 10, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Coffee plantation walk", "Abbey Falls", "Jungle safari"]', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80', 4.6, 87, 0, 0, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'madikeri'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'coorg-retreat');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Andaman Island Escape', 'andaman-escape', 'TBF-ANDAMAN-ES-106', 'Beach', 'group', 'Andaman Island Escape covering Port Blair · Havelock in Andaman & Nicobar — a 6 day 5 night beach experience.', 'Andaman Island Escape covering Port Blair · Havelock in Andaman & Nicobar — a 6 day 5 night beach experience.', 6, 5, 'Port Blair', 'Havelock', 38000, 'INR', 12, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Scuba diving", "Radhanagar Beach", "Cellular Jail tour"]', 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80', 4.8, 230, 0, 0, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'port-blair-havelock'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'andaman-escape');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Varanasi Spiritual Journey', 'varanasi-spiritual', 'TBF-VARANASI-S-107', 'Religious', 'group', 'Varanasi Spiritual Journey covering Varanasi in Uttar Pradesh — a 3 day 2 night religious experience.', 'Varanasi Spiritual Journey covering Varanasi in Uttar Pradesh — a 3 day 2 night religious experience.', 3, 2, 'Varanasi', 'Varanasi', 9800, 'INR', 15, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Ganga Aarti", "Sunrise boat ride", "Sarnath visit"]', 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80', 4.7, 176, 0, 0, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'varanasi'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'varanasi-spiritual');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Manali Adventure & Snow', 'manali-adventure', 'TBF-MANALI-ADV-108', 'Adventure', 'group', 'Manali Adventure & Snow covering Manali in Himachal Pradesh — a 6 day 5 night adventure experience.', 'Manali Adventure & Snow covering Manali in Himachal Pradesh — a 6 day 5 night adventure experience.', 6, 5, 'Delhi', 'Manali', 22000, 'INR', 12, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Rohtang Pass", "River rafting", "Solang Valley zip-line"]', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80', 4.7, 289, 0, 1, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'manali'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'manali-adventure');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Goa Sun, Sand & Seafood', 'goa-beaches', 'TBF-GOA-BEACHE-109', 'Beach', 'group', 'Goa Sun, Sand & Seafood covering North & South Goa in Goa — a 5 day 4 night beach experience.', 'Goa Sun, Sand & Seafood covering North & South Goa in Goa — a 5 day 4 night beach experience.', 5, 4, 'Goa', 'Goa', 16500, 'INR', 15, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Beach hopping", "Water sports", "Spice plantation tour"]', 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80', 4.5, 341, 0, 0, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'north-south-goa'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'goa-beaches');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Ooty & Nilgiris Explorer', 'ooty-nilgiris', 'TBF-OOTY-NILGI-110', 'Hill Station', 'group', 'Ooty & Nilgiris Explorer covering Ooty in Tamil Nadu — a 4 day 3 night hill station experience.', 'Ooty & Nilgiris Explorer covering Ooty in Tamil Nadu — a 4 day 3 night hill station experience.', 4, 3, 'Coimbatore', 'Ooty', 12000, 'INR', 10, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Toy train ride", "Botanical Garden", "Tea estate walk"]', 'https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=600&q=80', 4.5, 112, 0, 0, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'ooty'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'ooty-nilgiris');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Golden Triangle — Delhi Agra Jaipur', 'golden-triangle', 'TBF-GOLDEN-TRI-111', 'Cultural', 'group', 'Golden Triangle — Delhi Agra Jaipur covering Delhi · Agra · Jaipur in Multi-State — a 6 day 5 night cultural experience.', 'Golden Triangle — Delhi Agra Jaipur covering Delhi · Agra · Jaipur in Multi-State — a 6 day 5 night cultural experience.', 6, 5, 'Delhi', 'Jaipur', 19500, 'INR', 12, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Taj Mahal sunrise", "Red Fort", "City Palace Jaipur"]', 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80', 4.8, 507, 0, 1, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'delhi-agra-jaipur'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'golden-triangle');

INSERT INTO tours (id, destination_id, title, slug, code, category, type, short_description, description, duration_days, duration_nights, start_location, end_location, base_price, currency, max_group_size, min_group_size, transport_included, inclusions, exclusions, highlights, featured_image, avg_rating, review_count, booking_count, is_featured, is_published, is_active, created_at, updated_at)
SELECT lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), d.id, 'Ladakh Land of High Passes', 'ladakh-expedition', 'TBF-LADAKH-EXP-112', 'Adventure', 'group', 'Ladakh Land of High Passes covering Leh · Nubra · Pangong in Ladakh — a 9 day 8 night adventure experience.', 'Ladakh Land of High Passes covering Leh · Nubra · Pangong in Ladakh — a 9 day 8 night adventure experience.', 9, 8, 'Leh', 'Leh', 45000, 'INR', 8, 1, 1, '["Accommodation", "Daily breakfast", "Transport as per itinerary", "Sightseeing as listed", "Professional tour guide"]', '["Airfare/train fare", "Personal expenses", "Travel insurance", "Anything not mentioned in inclusions"]', '["Pangong Lake", "Nubra Valley", "Khardung La pass"]', 'https://images.unsplash.com/photo-1597040663342-45b6af3d91a5?w=600&q=80', 4.9, 193, 0, 0, 1, 1, unixepoch(), unixepoch()
FROM destinations d WHERE d.slug = 'leh-nubra-pangong'
AND NOT EXISTS (SELECT 1 FROM tours WHERE slug = 'ladakh-expedition');