/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DomesticRouteRouteImport } from './routes/domestic/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HajjUmrahRouteRouteImport } from './routes/hajj-umrah/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as DomesticIndexRouteImport } from './routes/domestic/index'
import { Route as DomesticAboutRouteImport } from './routes/domestic/about'
import { Route as DomesticContactRouteImport } from './routes/domestic/contact'
import { Route as HajjUmrahIndexRouteImport } from './routes/hajj-umrah/index'
import { Route as HajjUmrahContactRouteImport } from './routes/hajj-umrah/contact'
import { Route as HajjUmrahCustomGroupRouteImport } from './routes/hajj-umrah/custom-group'
import { Route as HajjUmrahFaqRouteImport } from './routes/hajj-umrah/faq'
import { Route as HajjUmrahGalleryRouteImport } from './routes/hajj-umrah/gallery'
import { Route as HajjUmrahProcessRouteImport } from './routes/hajj-umrah/process'
import { Route as HajjUmrahVisaRouteImport } from './routes/hajj-umrah/visa'
import { Route as InternationalIndexRouteImport } from './routes/international/index'
import { Route as InvitationWebinarRouteImport } from './routes/invitation/webinar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'
import { Route as DomesticBookingsIndexRouteImport } from './routes/domestic/bookings/index'
import { Route as DomesticBookingsBookingIdRouteImport } from './routes/domestic/bookings/$bookingId'
import { Route as DomesticCancellationPolicyIndexRouteImport } from './routes/domestic/cancellation-policy/index'
import { Route as DomesticCustomTripIndexRouteImport } from './routes/domestic/custom-trip/index'
import { Route as DomesticDestinationsIndexRouteImport } from './routes/domestic/destinations/index'
import { Route as DomesticDestinationsSlugRouteImport } from './routes/domestic/destinations/$slug'
import { Route as DomesticPrivacyIndexRouteImport } from './routes/domestic/privacy/index'
import { Route as DomesticTermsIndexRouteImport } from './routes/domestic/terms/index'
import { Route as DomesticThemesIndexRouteImport } from './routes/domestic/themes/index'
import { Route as DomesticToursIndexRouteImport } from './routes/domestic/tours/index'
import { Route as HajjUmrahPackagesIndexRouteImport } from './routes/hajj-umrah/packages/index'
import { Route as DomesticToursSlugIndexRouteImport } from './routes/domestic/tours/$slug/index'
import { Route as DomesticToursSlugBookRouteImport } from './routes/domestic/tours/$slug/book'
import { Route as HajjUmrahPackagesPackageIdIndexRouteImport } from './routes/hajj-umrah/packages/$packageId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomesticRouteRoute = DomesticRouteRouteImport.update({
  id: '/domestic',
  path: '/domestic',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjUmrahRouteRoute = HajjUmrahRouteRouteImport.update({
  id: '/hajj-umrah',
  path: '/hajj-umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DomesticIndexRoute = DomesticIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const DomesticAboutRoute = DomesticAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const DomesticContactRoute = DomesticContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const HajjUmrahIndexRoute = HajjUmrahIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HajjUmrahRouteRoute,
} as any)
const HajjUmrahContactRoute = HajjUmrahContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HajjUmrahRouteRoute,
} as any)
const HajjUmrahCustomGroupRoute = HajjUmrahCustomGroupRouteImport.update({
  id: '/custom-group',
  path: '/custom-group',
  getParentRoute: () => HajjUmrahRouteRoute,
} as any)
const HajjUmrahFaqRoute = HajjUmrahFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => HajjUmrahRouteRoute,
} as any)
const HajjUmrahGalleryRoute = HajjUmrahGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => HajjUmrahRouteRoute,
} as any)
const HajjUmrahProcessRoute = HajjUmrahProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => HajjUmrahRouteRoute,
} as any)
const HajjUmrahVisaRoute = HajjUmrahVisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => HajjUmrahRouteRoute,
} as any)
const InternationalIndexRoute = InternationalIndexRouteImport.update({
  id: '/international/',
  path: '/international/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationWebinarRoute = InvitationWebinarRouteImport.update({
  id: '/invitation/webinar',
  path: '/invitation/webinar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const DomesticBookingsIndexRoute = DomesticBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const DomesticBookingsBookingIdRoute =
  DomesticBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => DomesticRouteRoute,
  } as any)
const DomesticCancellationPolicyIndexRoute =
  DomesticCancellationPolicyIndexRouteImport.update({
    id: '/cancellation-policy/',
    path: '/cancellation-policy/',
    getParentRoute: () => DomesticRouteRoute,
  } as any)
const DomesticCustomTripIndexRoute = DomesticCustomTripIndexRouteImport.update({
  id: '/custom-trip/',
  path: '/custom-trip/',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const DomesticDestinationsIndexRoute =
  DomesticDestinationsIndexRouteImport.update({
    id: '/destinations/',
    path: '/destinations/',
    getParentRoute: () => DomesticRouteRoute,
  } as any)
const DomesticDestinationsSlugRoute =
  DomesticDestinationsSlugRouteImport.update({
    id: '/destinations/$slug',
    path: '/destinations/$slug',
    getParentRoute: () => DomesticRouteRoute,
  } as any)
const DomesticPrivacyIndexRoute = DomesticPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const DomesticTermsIndexRoute = DomesticTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const DomesticThemesIndexRoute = DomesticThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const DomesticToursIndexRoute = DomesticToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const HajjUmrahPackagesIndexRoute = HajjUmrahPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => HajjUmrahRouteRoute,
} as any)
const DomesticToursSlugIndexRoute = DomesticToursSlugIndexRouteImport.update({
  id: '/tours/$slug/',
  path: '/tours/$slug/',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const DomesticToursSlugBookRoute = DomesticToursSlugBookRouteImport.update({
  id: '/tours/$slug/book',
  path: '/tours/$slug/book',
  getParentRoute: () => DomesticRouteRoute,
} as any)
const HajjUmrahPackagesPackageIdIndexRoute =
  HajjUmrahPackagesPackageIdIndexRouteImport.update({
    id: '/packages/$packageId/',
    path: '/packages/$packageId/',
    getParentRoute: () => HajjUmrahRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domestic': typeof DomesticRouteRouteWithChildren
  '/hajj-umrah': typeof HajjUmrahRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/domestic/about': typeof DomesticAboutRoute
  '/domestic/contact': typeof DomesticContactRoute
  '/hajj-umrah/contact': typeof HajjUmrahContactRoute
  '/hajj-umrah/custom-group': typeof HajjUmrahCustomGroupRoute
  '/hajj-umrah/faq': typeof HajjUmrahFaqRoute
  '/hajj-umrah/gallery': typeof HajjUmrahGalleryRoute
  '/hajj-umrah/process': typeof HajjUmrahProcessRoute
  '/hajj-umrah/visa': typeof HajjUmrahVisaRoute
  '/invitation/webinar': typeof InvitationWebinarRoute
  '/domestic/': typeof DomesticIndexRoute
  '/hajj-umrah/': typeof HajjUmrahIndexRoute
  '/international/': typeof InternationalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/domestic/bookings/$bookingId': typeof DomesticBookingsBookingIdRoute
  '/domestic/destinations/$slug': typeof DomesticDestinationsSlugRoute
  '/domestic/bookings/': typeof DomesticBookingsIndexRoute
  '/domestic/cancellation-policy/': typeof DomesticCancellationPolicyIndexRoute
  '/domestic/custom-trip/': typeof DomesticCustomTripIndexRoute
  '/domestic/destinations/': typeof DomesticDestinationsIndexRoute
  '/domestic/privacy/': typeof DomesticPrivacyIndexRoute
  '/domestic/terms/': typeof DomesticTermsIndexRoute
  '/domestic/themes/': typeof DomesticThemesIndexRoute
  '/domestic/tours/': typeof DomesticToursIndexRoute
  '/hajj-umrah/packages/': typeof HajjUmrahPackagesIndexRoute
  '/domestic/tours/$slug/book': typeof DomesticToursSlugBookRoute
  '/domestic/tours/$slug/': typeof DomesticToursSlugIndexRoute
  '/hajj-umrah/packages/$packageId/': typeof HajjUmrahPackagesPackageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/domestic/about': typeof DomesticAboutRoute
  '/domestic/contact': typeof DomesticContactRoute
  '/hajj-umrah/contact': typeof HajjUmrahContactRoute
  '/hajj-umrah/custom-group': typeof HajjUmrahCustomGroupRoute
  '/hajj-umrah/faq': typeof HajjUmrahFaqRoute
  '/hajj-umrah/gallery': typeof HajjUmrahGalleryRoute
  '/hajj-umrah/process': typeof HajjUmrahProcessRoute
  '/hajj-umrah/visa': typeof HajjUmrahVisaRoute
  '/invitation/webinar': typeof InvitationWebinarRoute
  '/domestic': typeof DomesticIndexRoute
  '/hajj-umrah': typeof HajjUmrahIndexRoute
  '/international': typeof InternationalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/domestic/bookings/$bookingId': typeof DomesticBookingsBookingIdRoute
  '/domestic/destinations/$slug': typeof DomesticDestinationsSlugRoute
  '/domestic/bookings': typeof DomesticBookingsIndexRoute
  '/domestic/cancellation-policy': typeof DomesticCancellationPolicyIndexRoute
  '/domestic/custom-trip': typeof DomesticCustomTripIndexRoute
  '/domestic/destinations': typeof DomesticDestinationsIndexRoute
  '/domestic/privacy': typeof DomesticPrivacyIndexRoute
  '/domestic/terms': typeof DomesticTermsIndexRoute
  '/domestic/themes': typeof DomesticThemesIndexRoute
  '/domestic/tours': typeof DomesticToursIndexRoute
  '/hajj-umrah/packages': typeof HajjUmrahPackagesIndexRoute
  '/domestic/tours/$slug/book': typeof DomesticToursSlugBookRoute
  '/domestic/tours/$slug': typeof DomesticToursSlugIndexRoute
  '/hajj-umrah/packages/$packageId': typeof HajjUmrahPackagesPackageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domestic': typeof DomesticRouteRouteWithChildren
  '/hajj-umrah': typeof HajjUmrahRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/domestic/about': typeof DomesticAboutRoute
  '/domestic/contact': typeof DomesticContactRoute
  '/hajj-umrah/contact': typeof HajjUmrahContactRoute
  '/hajj-umrah/custom-group': typeof HajjUmrahCustomGroupRoute
  '/hajj-umrah/faq': typeof HajjUmrahFaqRoute
  '/hajj-umrah/gallery': typeof HajjUmrahGalleryRoute
  '/hajj-umrah/process': typeof HajjUmrahProcessRoute
  '/hajj-umrah/visa': typeof HajjUmrahVisaRoute
  '/invitation/webinar': typeof InvitationWebinarRoute
  '/domestic/': typeof DomesticIndexRoute
  '/hajj-umrah/': typeof HajjUmrahIndexRoute
  '/international/': typeof InternationalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/domestic/bookings/$bookingId': typeof DomesticBookingsBookingIdRoute
  '/domestic/destinations/$slug': typeof DomesticDestinationsSlugRoute
  '/domestic/bookings/': typeof DomesticBookingsIndexRoute
  '/domestic/cancellation-policy/': typeof DomesticCancellationPolicyIndexRoute
  '/domestic/custom-trip/': typeof DomesticCustomTripIndexRoute
  '/domestic/destinations/': typeof DomesticDestinationsIndexRoute
  '/domestic/privacy/': typeof DomesticPrivacyIndexRoute
  '/domestic/terms/': typeof DomesticTermsIndexRoute
  '/domestic/themes/': typeof DomesticThemesIndexRoute
  '/domestic/tours/': typeof DomesticToursIndexRoute
  '/hajj-umrah/packages/': typeof HajjUmrahPackagesIndexRoute
  '/domestic/tours/$slug/book': typeof DomesticToursSlugBookRoute
  '/domestic/tours/$slug/': typeof DomesticToursSlugIndexRoute
  '/hajj-umrah/packages/$packageId/': typeof HajjUmrahPackagesPackageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domestic'
    | '/hajj-umrah'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/domestic/about'
    | '/domestic/contact'
    | '/hajj-umrah/contact'
    | '/hajj-umrah/custom-group'
    | '/hajj-umrah/faq'
    | '/hajj-umrah/gallery'
    | '/hajj-umrah/process'
    | '/hajj-umrah/visa'
    | '/invitation/webinar'
    | '/domestic/'
    | '/hajj-umrah/'
    | '/international/'
    | '/api/auth/$'
    | '/api/webhooks/razorpay'
    | '/domestic/bookings/$bookingId'
    | '/domestic/destinations/$slug'
    | '/domestic/bookings/'
    | '/domestic/cancellation-policy/'
    | '/domestic/custom-trip/'
    | '/domestic/destinations/'
    | '/domestic/privacy/'
    | '/domestic/terms/'
    | '/domestic/themes/'
    | '/domestic/tours/'
    | '/hajj-umrah/packages/'
    | '/domestic/tours/$slug/book'
    | '/domestic/tours/$slug/'
    | '/hajj-umrah/packages/$packageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/domestic/about'
    | '/domestic/contact'
    | '/hajj-umrah/contact'
    | '/hajj-umrah/custom-group'
    | '/hajj-umrah/faq'
    | '/hajj-umrah/gallery'
    | '/hajj-umrah/process'
    | '/hajj-umrah/visa'
    | '/invitation/webinar'
    | '/domestic'
    | '/hajj-umrah'
    | '/international'
    | '/api/auth/$'
    | '/api/webhooks/razorpay'
    | '/domestic/bookings/$bookingId'
    | '/domestic/destinations/$slug'
    | '/domestic/bookings'
    | '/domestic/cancellation-policy'
    | '/domestic/custom-trip'
    | '/domestic/destinations'
    | '/domestic/privacy'
    | '/domestic/terms'
    | '/domestic/themes'
    | '/domestic/tours'
    | '/hajj-umrah/packages'
    | '/domestic/tours/$slug/book'
    | '/domestic/tours/$slug'
    | '/hajj-umrah/packages/$packageId'
  id:
    | '__root__'
    | '/'
    | '/domestic'
    | '/hajj-umrah'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/domestic/about'
    | '/domestic/contact'
    | '/hajj-umrah/contact'
    | '/hajj-umrah/custom-group'
    | '/hajj-umrah/faq'
    | '/hajj-umrah/gallery'
    | '/hajj-umrah/process'
    | '/hajj-umrah/visa'
    | '/invitation/webinar'
    | '/domestic/'
    | '/hajj-umrah/'
    | '/international/'
    | '/api/auth/$'
    | '/api/webhooks/razorpay'
    | '/domestic/bookings/$bookingId'
    | '/domestic/destinations/$slug'
    | '/domestic/bookings/'
    | '/domestic/cancellation-policy/'
    | '/domestic/custom-trip/'
    | '/domestic/destinations/'
    | '/domestic/privacy/'
    | '/domestic/terms/'
    | '/domestic/themes/'
    | '/domestic/tours/'
    | '/hajj-umrah/packages/'
    | '/domestic/tours/$slug/book'
    | '/domestic/tours/$slug/'
    | '/hajj-umrah/packages/$packageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomesticRouteRoute: typeof DomesticRouteRouteWithChildren
  HajjUmrahRouteRoute: typeof HajjUmrahRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  InvitationWebinarRoute: typeof InvitationWebinarRoute
  InternationalIndexRoute: typeof InternationalIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domestic': {
      id: '/domestic'
      path: '/domestic'
      fullPath: '/domestic'
      preLoaderRoute: typeof DomesticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj-umrah': {
      id: '/hajj-umrah'
      path: '/hajj-umrah'
      fullPath: '/hajj-umrah'
      preLoaderRoute: typeof HajjUmrahRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domestic/': {
      id: '/domestic/'
      path: '/'
      fullPath: '/domestic/'
      preLoaderRoute: typeof DomesticIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/about': {
      id: '/domestic/about'
      path: '/about'
      fullPath: '/domestic/about'
      preLoaderRoute: typeof DomesticAboutRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/contact': {
      id: '/domestic/contact'
      path: '/contact'
      fullPath: '/domestic/contact'
      preLoaderRoute: typeof DomesticContactRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/hajj-umrah/': {
      id: '/hajj-umrah/'
      path: '/'
      fullPath: '/hajj-umrah/'
      preLoaderRoute: typeof HajjUmrahIndexRouteImport
      parentRoute: typeof HajjUmrahRouteRoute
    }
    '/hajj-umrah/contact': {
      id: '/hajj-umrah/contact'
      path: '/contact'
      fullPath: '/hajj-umrah/contact'
      preLoaderRoute: typeof HajjUmrahContactRouteImport
      parentRoute: typeof HajjUmrahRouteRoute
    }
    '/hajj-umrah/custom-group': {
      id: '/hajj-umrah/custom-group'
      path: '/custom-group'
      fullPath: '/hajj-umrah/custom-group'
      preLoaderRoute: typeof HajjUmrahCustomGroupRouteImport
      parentRoute: typeof HajjUmrahRouteRoute
    }
    '/hajj-umrah/faq': {
      id: '/hajj-umrah/faq'
      path: '/faq'
      fullPath: '/hajj-umrah/faq'
      preLoaderRoute: typeof HajjUmrahFaqRouteImport
      parentRoute: typeof HajjUmrahRouteRoute
    }
    '/hajj-umrah/gallery': {
      id: '/hajj-umrah/gallery'
      path: '/gallery'
      fullPath: '/hajj-umrah/gallery'
      preLoaderRoute: typeof HajjUmrahGalleryRouteImport
      parentRoute: typeof HajjUmrahRouteRoute
    }
    '/hajj-umrah/process': {
      id: '/hajj-umrah/process'
      path: '/process'
      fullPath: '/hajj-umrah/process'
      preLoaderRoute: typeof HajjUmrahProcessRouteImport
      parentRoute: typeof HajjUmrahRouteRoute
    }
    '/hajj-umrah/visa': {
      id: '/hajj-umrah/visa'
      path: '/visa'
      fullPath: '/hajj-umrah/visa'
      preLoaderRoute: typeof HajjUmrahVisaRouteImport
      parentRoute: typeof HajjUmrahRouteRoute
    }
    '/international/': {
      id: '/international/'
      path: '/international'
      fullPath: '/international/'
      preLoaderRoute: typeof InternationalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/webinar': {
      id: '/invitation/webinar'
      path: '/invitation/webinar'
      fullPath: '/invitation/webinar'
      preLoaderRoute: typeof InvitationWebinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domestic/bookings/': {
      id: '/domestic/bookings/'
      path: '/bookings'
      fullPath: '/domestic/bookings/'
      preLoaderRoute: typeof DomesticBookingsIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/bookings/$bookingId': {
      id: '/domestic/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/domestic/bookings/$bookingId'
      preLoaderRoute: typeof DomesticBookingsBookingIdRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/cancellation-policy/': {
      id: '/domestic/cancellation-policy/'
      path: '/cancellation-policy'
      fullPath: '/domestic/cancellation-policy/'
      preLoaderRoute: typeof DomesticCancellationPolicyIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/custom-trip/': {
      id: '/domestic/custom-trip/'
      path: '/custom-trip'
      fullPath: '/domestic/custom-trip/'
      preLoaderRoute: typeof DomesticCustomTripIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/destinations/': {
      id: '/domestic/destinations/'
      path: '/destinations'
      fullPath: '/domestic/destinations/'
      preLoaderRoute: typeof DomesticDestinationsIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/destinations/$slug': {
      id: '/domestic/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/domestic/destinations/$slug'
      preLoaderRoute: typeof DomesticDestinationsSlugRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/privacy/': {
      id: '/domestic/privacy/'
      path: '/privacy'
      fullPath: '/domestic/privacy/'
      preLoaderRoute: typeof DomesticPrivacyIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/terms/': {
      id: '/domestic/terms/'
      path: '/terms'
      fullPath: '/domestic/terms/'
      preLoaderRoute: typeof DomesticTermsIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/themes/': {
      id: '/domestic/themes/'
      path: '/themes'
      fullPath: '/domestic/themes/'
      preLoaderRoute: typeof DomesticThemesIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/tours/': {
      id: '/domestic/tours/'
      path: '/tours'
      fullPath: '/domestic/tours/'
      preLoaderRoute: typeof DomesticToursIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/hajj-umrah/packages/': {
      id: '/hajj-umrah/packages/'
      path: '/packages'
      fullPath: '/hajj-umrah/packages/'
      preLoaderRoute: typeof HajjUmrahPackagesIndexRouteImport
      parentRoute: typeof HajjUmrahRouteRoute
    }
    '/domestic/tours/$slug/': {
      id: '/domestic/tours/$slug/'
      path: '/tours/$slug'
      fullPath: '/domestic/tours/$slug/'
      preLoaderRoute: typeof DomesticToursSlugIndexRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/domestic/tours/$slug/book': {
      id: '/domestic/tours/$slug/book'
      path: '/tours/$slug/book'
      fullPath: '/domestic/tours/$slug/book'
      preLoaderRoute: typeof DomesticToursSlugBookRouteImport
      parentRoute: typeof DomesticRouteRoute
    }
    '/hajj-umrah/packages/$packageId/': {
      id: '/hajj-umrah/packages/$packageId/'
      path: '/packages/$packageId'
      fullPath: '/hajj-umrah/packages/$packageId/'
      preLoaderRoute: typeof HajjUmrahPackagesPackageIdIndexRouteImport
      parentRoute: typeof HajjUmrahRouteRoute
    }
  }
}

interface DomesticRouteRouteChildren {
  DomesticAboutRoute: typeof DomesticAboutRoute
  DomesticContactRoute: typeof DomesticContactRoute
  DomesticIndexRoute: typeof DomesticIndexRoute
  DomesticBookingsBookingIdRoute: typeof DomesticBookingsBookingIdRoute
  DomesticDestinationsSlugRoute: typeof DomesticDestinationsSlugRoute
  DomesticBookingsIndexRoute: typeof DomesticBookingsIndexRoute
  DomesticCancellationPolicyIndexRoute: typeof DomesticCancellationPolicyIndexRoute
  DomesticCustomTripIndexRoute: typeof DomesticCustomTripIndexRoute
  DomesticDestinationsIndexRoute: typeof DomesticDestinationsIndexRoute
  DomesticPrivacyIndexRoute: typeof DomesticPrivacyIndexRoute
  DomesticTermsIndexRoute: typeof DomesticTermsIndexRoute
  DomesticThemesIndexRoute: typeof DomesticThemesIndexRoute
  DomesticToursIndexRoute: typeof DomesticToursIndexRoute
  DomesticToursSlugBookRoute: typeof DomesticToursSlugBookRoute
  DomesticToursSlugIndexRoute: typeof DomesticToursSlugIndexRoute
}

const DomesticRouteRouteChildren: DomesticRouteRouteChildren = {
  DomesticAboutRoute: DomesticAboutRoute,
  DomesticContactRoute: DomesticContactRoute,
  DomesticIndexRoute: DomesticIndexRoute,
  DomesticBookingsBookingIdRoute: DomesticBookingsBookingIdRoute,
  DomesticDestinationsSlugRoute: DomesticDestinationsSlugRoute,
  DomesticBookingsIndexRoute: DomesticBookingsIndexRoute,
  DomesticCancellationPolicyIndexRoute: DomesticCancellationPolicyIndexRoute,
  DomesticCustomTripIndexRoute: DomesticCustomTripIndexRoute,
  DomesticDestinationsIndexRoute: DomesticDestinationsIndexRoute,
  DomesticPrivacyIndexRoute: DomesticPrivacyIndexRoute,
  DomesticTermsIndexRoute: DomesticTermsIndexRoute,
  DomesticThemesIndexRoute: DomesticThemesIndexRoute,
  DomesticToursIndexRoute: DomesticToursIndexRoute,
  DomesticToursSlugBookRoute: DomesticToursSlugBookRoute,
  DomesticToursSlugIndexRoute: DomesticToursSlugIndexRoute,
}

const DomesticRouteRouteWithChildren = DomesticRouteRoute._addFileChildren(
  DomesticRouteRouteChildren,
)

interface HajjUmrahRouteRouteChildren {
  HajjUmrahContactRoute: typeof HajjUmrahContactRoute
  HajjUmrahCustomGroupRoute: typeof HajjUmrahCustomGroupRoute
  HajjUmrahFaqRoute: typeof HajjUmrahFaqRoute
  HajjUmrahGalleryRoute: typeof HajjUmrahGalleryRoute
  HajjUmrahProcessRoute: typeof HajjUmrahProcessRoute
  HajjUmrahVisaRoute: typeof HajjUmrahVisaRoute
  HajjUmrahIndexRoute: typeof HajjUmrahIndexRoute
  HajjUmrahPackagesIndexRoute: typeof HajjUmrahPackagesIndexRoute
  HajjUmrahPackagesPackageIdIndexRoute: typeof HajjUmrahPackagesPackageIdIndexRoute
}

const HajjUmrahRouteRouteChildren: HajjUmrahRouteRouteChildren = {
  HajjUmrahContactRoute: HajjUmrahContactRoute,
  HajjUmrahCustomGroupRoute: HajjUmrahCustomGroupRoute,
  HajjUmrahFaqRoute: HajjUmrahFaqRoute,
  HajjUmrahGalleryRoute: HajjUmrahGalleryRoute,
  HajjUmrahProcessRoute: HajjUmrahProcessRoute,
  HajjUmrahVisaRoute: HajjUmrahVisaRoute,
  HajjUmrahIndexRoute: HajjUmrahIndexRoute,
  HajjUmrahPackagesIndexRoute: HajjUmrahPackagesIndexRoute,
  HajjUmrahPackagesPackageIdIndexRoute: HajjUmrahPackagesPackageIdIndexRoute,
}

const HajjUmrahRouteRouteWithChildren = HajjUmrahRouteRoute._addFileChildren(
  HajjUmrahRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomesticRouteRoute: DomesticRouteRouteWithChildren,
  HajjUmrahRouteRoute: HajjUmrahRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  InvitationWebinarRoute: InvitationWebinarRoute,
  InternationalIndexRoute: InternationalIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
