import { Globe2, MapPinned, MoonStar } from "lucide-react";

export const bookingOptions = [
  {
    title: "Domestic Tours",
    description:
    "Local touring spots, weekend escapes, and custom group plans.",
    to: "/domestic",
    image:
    "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    icon: MapPinned,
    label: "Local experiences",
  },
  {
    title: "Hajj & Umrah",
    description: "Pilgrimage packages, visa support, Makkah and Madinah stays.",
    to: "/hajj-umrah",
    image:
      "https://images.unsplash.com/photo-1580418827493-f2b22c0a76cb?auto=format&fit=crop&w=900&q=80",
    icon: MoonStar,
    label: "Religious travel",
  },
  {
    title: "International Trips",
    description:
      "Holiday packages, family trips, flights, hotels, and itineraries.",
    to: "/international",
    image:
      "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=900&q=80",
    icon: Globe2,
    label: "Global holidays",
  },
] as const;

const ALL_TOURS = [
  {
    id: "kerala-backwaters",
    title: "Kerala Backwaters & Spice Trail",
    destination: "Alleppey",
    state: "Kerala",
    duration: "5D / 4N",
    durationDays: 5,
    price: 18500,
    rating: 4.9,
    reviewCount: 312,
    category: "Beach",
    image:
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    tag: "Best Seller",
    groupSize: 12,
    highlights: ["Houseboat stay", "Spice plantation", "Kathakali show"],
  },
  {
    id: "rajasthan-royals",
    title: "Royal Rajasthan Heritage Tour",
    destination: "Jaipur → Jodhpur → Udaipur",
    state: "Rajasthan",
    duration: "7D / 6N",
    durationDays: 7,
    price: 24999,
    rating: 4.8,
    reviewCount: 198,
    category: "Cultural",
    image:
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
    tag: "Popular",
    groupSize: 10,
    highlights: ["Amber Fort", "Desert safari", "Lake Pichola cruise"],
  },
  {
    id: "spiti-valley",
    title: "Spiti Valley Expedition",
    destination: "Kaza",
    state: "Himachal Pradesh",
    duration: "8D / 7N",
    durationDays: 8,
    price: 32000,
    rating: 4.7,
    reviewCount: 145,
    category: "Adventure",
    image:
      "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
    tag: "New",
    groupSize: 8,
    highlights: ["Key Monastery", "Chandratal Lake", "4WD off-roading"],
  },
  {
    id: "char-dham",
    title: "Char Dham Yatra",
    destination: "Badrinath · Kedarnath · Gangotri · Yamunotri",
    state: "Uttarakhand",
    duration: "12D / 11N",
    durationDays: 12,
    price: 42000,
    rating: 4.9,
    reviewCount: 421,
    category: "Religious",
    image:
      "https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=600&q=80",
    tag: "Best Seller",
    groupSize: 15,
    highlights: ["4 sacred shrines", "Helicopter option", "Vedic rituals"],
  },
  {
    id: "coorg-retreat",
    title: "Coorg Coffee & Nature Retreat",
    destination: "Madikeri",
    state: "Karnataka",
    duration: "4D / 3N",
    durationDays: 4,
    price: 14500,
    rating: 4.6,
    reviewCount: 87,
    category: "Hill Station",
    image:
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
    groupSize: 10,
    highlights: ["Coffee plantation walk", "Abbey Falls", "Jungle safari"],
  },
  {
    id: "andaman-escape",
    title: "Andaman Island Escape",
    destination: "Port Blair · Havelock",
    state: "Andaman & Nicobar",
    duration: "6D / 5N",
    durationDays: 6,
    price: 38000,
    rating: 4.8,
    reviewCount: 230,
    category: "Beach",
    image:
      "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80",
    groupSize: 12,
    highlights: ["Scuba diving", "Radhanagar Beach", "Cellular Jail tour"],
  },
  {
    id: "varanasi-spiritual",
    title: "Varanasi Spiritual Journey",
    destination: "Varanasi",
    state: "Uttar Pradesh",
    duration: "3D / 2N",
    durationDays: 3,
    price: 9800,
    rating: 4.7,
    reviewCount: 176,
    category: "Religious",
    image:
      "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80",
    groupSize: 15,
    highlights: ["Ganga Aarti", "Sunrise boat ride", "Sarnath visit"],
  },
  {
    id: "manali-adventure",
    title: "Manali Adventure & Snow",
    destination: "Manali",
    state: "Himachal Pradesh",
    duration: "6D / 5N",
    durationDays: 6,
    price: 22000,
    rating: 4.7,
    reviewCount: 289,
    category: "Adventure",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    tag: "Popular",
    groupSize: 12,
    highlights: ["Rohtang Pass", "River rafting", "Solang Valley zip-line"],
  },
  {
    id: "goa-beaches",
    title: "Goa Sun, Sand & Seafood",
    destination: "North & South Goa",
    state: "Goa",
    duration: "5D / 4N",
    durationDays: 5,
    price: 16500,
    rating: 4.5,
    reviewCount: 341,
    category: "Beach",
    image:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80",
    groupSize: 15,
    highlights: ["Beach hopping", "Water sports", "Spice plantation tour"],
  },
  {
   id: "ooty-nilgiris",
    title: "Ooty & Nilgiris Explorer",
    destination: "Ooty",
    state: "Tamil Nadu",
    duration: "4D / 3N",
    durationDays: 4,
    price: 12000,
    rating: 4.5,
    reviewCount: 112,
    category: "Hill Station",
    image:
      "https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=600&q=80",
    groupSize: 10,
    highlights: ["Toy train ride", "Botanical Garden", "Tea estate walk"],
  },
  {
    id: "golden-triangle",
    title: "Golden Triangle — Delhi Agra Jaipur",
    destination: "Delhi · Agra · Jaipur",
    state: "Multi-State",
    duration: "6D / 5N",
    durationDays: 6,
    price: 19500,
    rating: 4.8,
    reviewCount: 507,
    category: "Cultural",
    tag: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    groupSize: 12,
    highlights: ["Taj Mahal sunrise", "Red Fort", "City Palace Jaipur"],
  },
  {
    id: "ladakh-expedition",
    title: "Ladakh Land of High Passes",
    destination: "Leh · Nubra · Pangong",
    state: "Ladakh",
    duration: "9D / 8N",
    durationDays: 9,
    price: 45000,
    rating: 4.9,
    reviewCount: 193,
    category: "Adventure",
    image:
      "https://images.unsplash.com/photo-1597040663342-45b6af3d91a5?w=600&q=80",
    groupSize: 8,
    highlights: ["Pangong Lake", "Nubra Valley", "Khardung La pass"],
  },
];