import { Globe2, MapPinned, MoonStar } from "lucide-react";

export const bookingOptions = [
  {
    title: "Domestic Tours",
    description:
      "Local touring spots, weekend escapes, and custom group plans.",
    to: "/domestic",
    image:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    icon: MapPinned,
    label: "Local experiences",
  },
  {
    title: "Hajj & Umrah",
    description: "Pilgrimage packages, visa support, Makkah and Madinah stays.",
    to: "/hajj-umrah",
    image:
      "https://images.unsplash.com/photo-1580418827493-f2b22c0a76cb?auto=format&fit=crop&w=900&q=80",
    icon: MoonStar,
    label: "Religious travel",
  },
  {
    title: "International Trips",
    description:
      "Holiday packages, family trips, flights, hotels, and itineraries.",
    to: "/international",
    image:
      "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=900&q=80",
    icon: Globe2,
    label: "Global holidays",
  },
] as const;

const ALL_TOURS = [
  {
    id: "kerala-backwaters",
    title: "Kerala Backwaters & Spice Trail",
    destination: "Alleppey",
    state: "Kerala",
    duration: "5D / 4N",
    durationDays: 5,
    price: 18500,
    rating: 4.9,
    reviewCount: 312,
    category: "Beach",
    image:
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    tag: "Best Seller",
    groupSize: 12,
    highlights: ["Houseboat stay", "Spice plantation", "Kathakali show"],
  },
  {
    id: "rajasthan-royals",
    title: "Royal Rajasthan Heritage Tour",
    destination: "Jaipur → Jodhpur → Udaipur",
    state: "Rajasthan",
    duration: "7D / 6N",
    durationDays: 7,
    price: 24999,
    rating: 4.8,
    reviewCount: 198,
    category: "Cultural",
    image:
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
    tag: "Popular",
    groupSize: 10,
    highlights: ["Amber Fort", "Desert safari", "Lake Pichola cruise"],
  },
  {
    id: "spiti-valley",
    title: "Spiti Valley Expedition",
    destination: "Kaza",
    state: "Himachal Pradesh",
    duration: "8D / 7N",
    durationDays: 8,
    price: 32000,
    rating: 4.7,
    reviewCount: 145,
    category: "Adventure",
    image:
      "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
    tag: "New",
    groupSize: 8,
    highlights: ["Key Monastery", "Chandratal Lake", "4WD off-roading"],
  },
  {
    id: "char-dham",
    title: "Char Dham Yatra",
    destination: "Badrinath · Kedarnath · Gangotri · Yamunotri",
    state: "Uttarakhand",
    duration: "12D / 11N",
    durationDays: 12,
    price: 42000,
    rating: 4.9,
    reviewCount: 421,
    category: "Religious",
    image:
      "https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=600&q=80",
    tag: "Best Seller",
    groupSize: 15,
    highlights: ["4 sacred shrines", "Helicopter option", "Vedic rituals"],
  },
  {
    id: "coorg-retreat",
    title: "Coorg Coffee & Nature Retreat",
    destination: "Madikeri",
    state: "Karnataka",
    duration: "4D / 3N",
    durationDays: 4,
    price: 14500,
    rating: 4.6,
    reviewCount: 87,
    category: "Hill Station",
    image:
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
    groupSize: 10,
    highlights: ["Coffee plantation walk", "Abbey Falls", "Jungle safari"],
  },
  {
    id: "andaman-escape",
    title: "Andaman Island Escape",
    destination: "Port Blair · Havelock",
    state: "Andaman & Nicobar",
    duration: "6D / 5N",
    durationDays: 6,
    price: 38000,
    rating: 4.8,
    reviewCount: 230,
    category: "Beach",
    image:
      "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80",
    groupSize: 12,
    highlights: ["Scuba diving", "Radhanagar Beach", "Cellular Jail tour"],
  },
  {
    id: "varanasi-spiritual",
    title: "Varanasi Spiritual Journey",
    destination: "Varanasi",
    state: "Uttar Pradesh",
    duration: "3D / 2N",
    durationDays: 3,
    price: 9800,
    rating: 4.7,
    reviewCount: 176,
    category: "Religious",
    image:
      "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80",
    groupSize: 15,
    highlights: ["Ganga Aarti", "Sunrise boat ride", "Sarnath visit"],
  },
  {
    id: "manali-adventure",
    title: "Manali Adventure & Snow",
    destination: "Manali",
    state: "Himachal Pradesh",
    duration: "6D / 5N",
    durationDays: 6,
    price: 22000,
    rating: 4.7,
    reviewCount: 289,
    category: "Adventure",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    tag: "Popular",
    groupSize: 12,
    highlights: ["Rohtang Pass", "River rafting", "Solang Valley zip-line"],
  },
  {
    id: "goa-beaches",
    title: "Goa Sun, Sand & Seafood",
    destination: "North & South Goa",
    state: "Goa",
    duration: "5D / 4N",
    durationDays: 5,
    price: 16500,
    rating: 4.5,
    reviewCount: 341,
    category: "Beach",
    image:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80",
    groupSize: 15,
    highlights: ["Beach hopping", "Water sports", "Spice plantation tour"],
  },
  {
    id: "ooty-nilgiris",
    title: "Ooty & Nilgiris Explorer",
    destination: "Ooty",
    state: "Tamil Nadu",
    duration: "4D / 3N",
    durationDays: 4,
    price: 12000,
    rating: 4.5,
    reviewCount: 112,
    category: "Hill Station",
    image:
      "https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=600&q=80",
    groupSize: 10,
    highlights: ["Toy train ride", "Botanical Garden", "Tea estate walk"],
  },
  {
    id: "golden-triangle",
    title: "Golden Triangle — Delhi Agra Jaipur",
    destination: "Delhi · Agra · Jaipur",
    state: "Multi-State",
    duration: "6D / 5N",
    durationDays: 6,
    price: 19500,
    rating: 4.8,
    reviewCount: 507,
    category: "Cultural",
    tag: "Best Seller",
    image:
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    groupSize: 12,
    highlights: ["Taj Mahal sunrise", "Red Fort", "City Palace Jaipur"],
  },
  {
    id: "ladakh-expedition",
    title: "Ladakh Land of High Passes",
    destination: "Leh · Nubra · Pangong",
    state: "Ladakh",
    duration: "9D / 8N",
    durationDays: 9,
    price: 45000,
    rating: 4.9,
    reviewCount: 193,
    category: "Adventure",
    image:
      "https://images.unsplash.com/photo-1597040663342-45b6af3d91a5?w=600&q=80",
    groupSize: 8,
    highlights: ["Pangong Lake", "Nubra Valley", "Khardung La pass"],
  },
];

export const DESTINATIONS_LOCAL_DATA = [
  // ── North ──────────────────────────────────────────────────────────────────
  {
    id: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    region: "North",
    category: ["Cultural"],
    tagline: "The Pink City of palaces, forts & desert royalty",
    tourCount: 31,
    rating: 4.8,
    bestTime: "Oct – Mar",
    image:
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
    highlights: ["Amber Fort", "Hawa Mahal", "City Palace"],
    trending: true,
  },
  {
    id: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    region: "North",
    category: ["Religious", "Cultural"],
    tagline: "India's spiritual capital on the sacred Ganga",
    tourCount: 18,
    rating: 4.7,
    bestTime: "Nov – Mar",
    image:
      "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80",
    highlights: ["Ganga Aarti", "Sarnath", "Kashi Vishwanath"],
    trending: true,
  },
  {
    id: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    region: "North",
    category: ["Cultural"],
    tagline: "Home of the eternal Taj Mahal & Mughal grandeur",
    tourCount: 22,
    rating: 4.9,
    bestTime: "Oct – Mar",
    image:
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    highlights: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri"],
  },
  {
    id: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    region: "North",
    category: ["Hill Station", "Adventure"],
    tagline: "Snow peaks, river valleys & Himalayan thrills",
    tourCount: 24,
    rating: 4.7,
    bestTime: "Mar – Jun, Oct – Feb",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    highlights: ["Rohtang Pass", "Solang Valley", "Old Manali"],
    trending: true,
  },
  {
    id: "leh-ladakh",
    name: "Leh Ladakh",
    state: "Ladakh",
    region: "North",
    category: ["Adventure", "Cultural"],
    tagline: "The land of high passes, monasteries & starry skies",
    tourCount: 15,
    rating: 4.9,
    bestTime: "Jun – Sep",
    image:
      "https://images.unsplash.com/photo-1597040663342-45b6af3d91a5?w=600&q=80",
    highlights: ["Pangong Lake", "Nubra Valley", "Khardung La"],
    trending: true,
  },
  {
    id: "jodhpur",
    name: "Jodhpur",
    state: "Rajasthan",
    region: "North",
    category: ["Cultural"],
    tagline: "The Blue City — a maze of indigo rooftops and forts",
    tourCount: 19,
    rating: 4.7,
    bestTime: "Oct – Mar",
    image:
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&q=80",
    highlights: ["Mehrangarh Fort", "Blue City", "Umaid Bhawan"],
  },
  {
    id: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    region: "North",
    category: ["Adventure", "Religious"],
    tagline: "Yoga capital of the world & gateway to the Himalayas",
    tourCount: 14,
    rating: 4.6,
    bestTime: "Sep – Jun",
    image:
      "https://images.unsplash.com/photo-1545579133-99bb5ab189bd?w=600&q=80",
    highlights: ["River Rafting", "Laxman Jhula", "Bungee Jumping"],
  },

  // ── South ──────────────────────────────────────────────────────────────────
  {
    id: "kerala",
    name: "Kerala",
    state: "Kerala",
    region: "South",
    category: ["Beach", "Cultural"],
    tagline: "God's Own Country — backwaters, spices & lush greenery",
    tourCount: 27,
    rating: 4.9,
    bestTime: "Oct – Mar",
    image:
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    highlights: ["Alleppey Backwaters", "Munnar", "Fort Kochi"],
    trending: true,
  },
  {
    id: "coorg",
    name: "Coorg",
    state: "Karnataka",
    region: "South",
    category: ["Hill Station", "Wildlife"],
    tagline: "Scotland of India — coffee, mist & jungle trails",
    tourCount: 12,
    rating: 4.6,
    bestTime: "Oct – Mar",
    image:
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
    highlights: ["Coffee Plantations", "Abbey Falls", "Nagarhole"],
  },
  {
    id: "ooty",
    name: "Ooty",
    state: "Tamil Nadu",
    region: "South",
    category: ["Hill Station"],
    tagline: "Queen of hill stations in the Nilgiri mountains",
    tourCount: 10,
    rating: 4.5,
    bestTime: "Apr – Jun, Sep – Nov",
    image:
      "https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=600&q=80",
    highlights: ["Toy Train", "Botanical Garden", "Doddabetta Peak"],
  },
  {
    id: "mysuru",
    name: "Mysuru",
    state: "Karnataka",
    region: "South",
    category: ["Cultural"],
    tagline: "City of palaces, sandalwood & the Dasara festival",
    tourCount: 14,
    rating: 4.7,
    bestTime: "Oct – Mar",
    image:
      "https://images.unsplash.com/photo-1590050751974-7b5d5b5d5aca?w=600&q=80",
    highlights: ["Mysore Palace", "Chamundi Hills", "Brindavan Garden"],
  },
  {
    id: "hampi",
    name: "Hampi",
    state: "Karnataka",
    region: "South",
    category: ["Cultural", "Adventure"],
    tagline: "UNESCO ruins of the Vijayanagara Empire among boulders",
    tourCount: 9,
    rating: 4.8,
    bestTime: "Oct – Feb",
    image:
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&q=80",
    highlights: ["Virupaksha Temple", "Stone Chariot", "Hippie Island"],
    trending: true,
  },

  // ── East ───────────────────────────────────────────────────────────────────
  {
    id: "darjeeling",
    name: "Darjeeling",
    state: "West Bengal",
    region: "East",
    category: ["Hill Station"],
    tagline: "Toy trains, tea estates & Kangchenjunga views",
    tourCount: 11,
    rating: 4.7,
    bestTime: "Mar – May, Sep – Nov",
    image:
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
    highlights: ["Tiger Hill Sunrise", "Toy Train", "Tea Garden Walk"],
  },
  {
    id: "puri",
    name: "Puri",
    state: "Odisha",
    region: "East",
    category: ["Beach", "Religious"],
    tagline: "Sacred beaches & the grand Jagannath Temple",
    tourCount: 8,
    rating: 4.5,
    bestTime: "Nov – Feb",
    image:
      "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80",
    highlights: ["Jagannath Temple", "Puri Beach", "Konark Sun Temple"],
  },
  {
    id: "gangtok",
    name: "Gangtok",
    state: "Sikkim",
    region: "East",
    category: ["Hill Station", "Adventure"],
    tagline: "Himalayan hill capital with monasteries & mountain views",
    tourCount: 7,
    rating: 4.6,
    bestTime: "Mar – May, Oct – Dec",
    image:
      "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
    highlights: ["Rumtek Monastery", "Tsomgo Lake", "Nathu La Pass"],
  },

  // ── West ───────────────────────────────────────────────────────────────────
  {
    id: "goa",
    name: "Goa",
    state: "Goa",
    region: "West",
    category: ["Beach"],
    tagline: "India's sun-soaked beach paradise with Portuguese soul",
    tourCount: 24,
    rating: 4.6,
    bestTime: "Nov – Mar",
    image:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80",
    highlights: ["Baga Beach", "Old Goa Churches", "Dudhsagar Falls"],
    trending: true,
  },
  {
    id: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    region: "West",
    category: ["Cultural"],
    tagline: "The city that never sleeps — Bollywood, food & history",
    tourCount: 16,
    rating: 4.5,
    bestTime: "Nov – Feb",
    image:
      "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=600&q=80",
    highlights: ["Gateway of India", "Marine Drive", "Elephanta Caves"],
  },
  {
    id: "rann-of-kutch",
    name: "Rann of Kutch",
    state: "Gujarat",
    region: "West",
    category: ["Cultural", "Adventure"],
    tagline: "The great white salt desert under the full moon",
    tourCount: 10,
    rating: 4.8,
    bestTime: "Nov – Feb",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    highlights: ["White Desert", "Rann Utsav", "Dholavira"],
    trending: true,
  },
  {
    id: "lonavala",
    name: "Lonavala",
    state: "Maharashtra",
    region: "West",
    category: ["Hill Station"],
    tagline: "Mumbai's misty weekend escape in the Sahyadri range",
    tourCount: 9,
    rating: 4.4,
    bestTime: "Jun – Sep, Nov – Feb",
    image:
      "https://images.unsplash.com/photo-1543158181-e6f9f6712055?w=600&q=80",
    highlights: ["Bhushi Dam", "Rajmachi Fort", "Karla Caves"],
  },

  // ── Central ────────────────────────────────────────────────────────────────
  {
    id: "khajuraho",
    name: "Khajuraho",
    state: "Madhya Pradesh",
    region: "Central",
    category: ["Cultural"],
    tagline: "UNESCO temples of extraordinary medieval stone sculptures",
    tourCount: 8,
    rating: 4.7,
    bestTime: "Oct – Mar",
    image:
      "https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=600&q=80",
    highlights: [
      "Western Temples",
      "Light & Sound Show",
      "Panna Tiger Reserve",
    ],
  },
  {
    id: "kanha",
    name: "Kanha",
    state: "Madhya Pradesh",
    region: "Central",
    category: ["Wildlife"],
    tagline: "Inspired The Jungle Book — prime tiger & barasingha territory",
    tourCount: 6,
    rating: 4.8,
    bestTime: "Oct – Jun",
    image:
      "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=600&q=80",
    highlights: ["Tiger Safari", "Barasingha", "Bamni Dadar"],
  },

  // ── Islands ────────────────────────────────────────────────────────────────
  {
    id: "andaman",
    name: "Andaman & Nicobar",
    state: "Andaman & Nicobar",
    region: "Islands",
    category: ["Beach", "Adventure"],
    tagline: "Turquoise waters, coral reefs & a pristine island world",
    tourCount: 14,
    rating: 4.8,
    bestTime: "Nov – May",
    image:
      "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80",
    highlights: ["Radhanagar Beach", "Scuba Diving", "Cellular Jail"],
    trending: true,
  },
  {
    id: "lakshadweep",
    name: "Lakshadweep",
    state: "Lakshadweep",
    region: "Islands",
    category: ["Beach"],
    tagline: "India's coral island paradise — untouched & serene",
    tourCount: 5,
    rating: 4.9,
    bestTime: "Oct – May",
    image:
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80",
    highlights: ["Agatti Island", "Snorkelling", "Lagoon Stay"],
  },
];
